# Sample Role for running Kubernetes jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controlm-agent-job-privileges
  namespace: controlm-job-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-executor
subjects:
- kind: ServiceAccount
  name: svc-controlm-agent-local
  namespace: controlm-agent-namespace
